# Generated by Django 3.0.4 on 2020-04-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_gstworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstworker',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
