# Generated by Django 3.0.4 on 2020-04-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_gstworker_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstworker',
            name='r_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
